before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build lab01/cs101F2018_lab01.tex
- latexmk -pdf -outdir=_build lab02/cs101F2018_lab02.tex
- latexmk -pdf -outdir=_build lab03/cs101F2018_lab03.tex
- latexmk -pdf -outdir=_build lab04/cs101F2018_lab04.tex
- latexmk -pdf -outdir=_build lab05/cs101F2018_lab05.tex
- latexmk -pdf -outdir=_build lab06/cs101F2018_lab06.tex
- latexmk -pdf -outdir=_build lab07/cs101F2018_lab07.tex
- latexmk -pdf -outdir=_build lab08/cs101F2018_lab08.tex
- latexmk -pdf -outdir=_build practical01/cs101F2018_practical01.tex
- latexmk -pdf -outdir=_build practical02/cs101F2018_practical02.tex
- latexmk -pdf -outdir=_build practical03/cs101F2018_practical03.tex
- latexmk -pdf -outdir=_build practical04/cs101F2018_practical04.tex
- latexmk -pdf -outdir=_build practical05/cs101F2018_practical05.tex
- latexmk -pdf -outdir=_build practical06/cs101F2018_practical06.tex
- latexmk -pdf -outdir=_build practical07/cs101F2018_practical07.tex
- latexmk -pdf -outdir=_build practical08/cs101F2018_practical08.tex
- latexmk -pdf -outdir=_build quiz01/cs101F2018_studyguide_quiz01.tex
- latexmk -pdf -outdir=_build exam01/cs101F2018_studyguide_exam01.tex
- latexmk -pdf -outdir=_build quiz02/cs101F2018_studyguide_quiz02.tex
deploy:
  provider: releases
  api_key:
    secure: mrtJ894fXLpCdE9aZ4BU/WCM8P488lVWW6OqX/Qgr1zUA6vHLe2NIS0cawuQDsNnTH8F/4/Xo8FggeNs+uleHEUij0tU7hrWtsbIJyfhDRfKTwq5guRKndWhTRc/mGsKGpz5IG+y881GjVckSZJuE8woUQVLv824nbTlvRqvTqwUNaq6FtdXSbfT+vuF1g4VLlEG+zWZXEeHxirWNmgvd4nuny0XJ9JiDr3zNr6ELwRTF2Z7mgupnTThf+VdLFBJCNce93o0Nt6P9fwTPr7uhYzm0utVP/C45eXPzBGV21yqvCGefSBs5XWxi7p3cQ1LkgJMXrcJn5gOARtvfDSeOe8Ho+o/xvNHO27z6/1mmEnNynYCvjVkmsPi04SXeDgRgSdY3+n3796ZnX4ZL1lROwJLcFJ+xu1bk7GT3V51y5oTDPS+LCxnA7pkeKtnjtgkZXf91/SQQ5rWaWT1JVZDAKvNpA25R2bXDDGFQUcNPirU8idtXhAs+7pAWu11xxyQ98X5HX0Z8VUfvWbVclkhxxuj72EMy5pzLUX0S+kL/nuUZqExbChT1V4fvzZPnalEO4WO58I3zYhw4pyEQKa9pQIy/j8kPhpmtMce/vGhoQh87SadOxyFQELwAanPSTL4p22LIUwkjKKDWNChp9Fo0BBHdCo1mYFpDk/aoD+vNBA=
  file:
    - _build/cs101F2018_lab01.pdf
    - _build/cs101F2018_lab02.pdf
    - _build/cs101F2018_lab03.pdf
    - _build/cs101F2018_lab04.pdf
    - _build/cs101F2018_lab05.pdf
    - _build/cs101F2018_lab06.pdf
    - _build/cs101F2018_lab07.pdf
    - _build/cs101F2018_lab08.pdf
    - _build/cs101F2018_practical01.pdf
    - _build/cs101F2018_practical02.pdf
    - _build/cs101F2018_practical03.pdf
    - _build/cs101F2018_practical04.pdf
    - _build/cs101F2018_practical05.pdf
    - _build/cs101F2018_practical06.pdf
    - _build/cs101F2018_practical07.pdf
    - _build/cs101F2018_practical08.pdf
    - _build/cs101F2018_studyguide_quiz01.pdf
    - _build/cs101F2018_studyguide_quiz02.pdf
    - _build/cs101F2018_studyguide_exam01.pdf
  skip_cleanup: true
  on:
    tags: true
